version: '3.1'

services:
  booking-system:
    build: .
    depends_on:
      - "db"
    ports:
      - "8080:8080"
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"

